/* Generated by re2c 1.1.1 on Sun Feb 17 10:21:40 2019 */
#line 1 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
#include <cstdio>
#include "expr_lexer.h"

#define YYMAXFILL 18


bool ExprLexer::Context::fill(size_t need)
{
    if(eof)
        return false;
    
    const size_t free = tok - buf;
    if(free<need)
        return false;

    memmove(buf, tok, lim-tok);
    lim -= free;
    cur -= free;
    tok -= free;
    in.read(buf,free);
    lim += in.gcount();
    
    if(lim < buf + free)
    {
        eof = true;
        memset(lim,0,YYMAXFILL);
        lim+=YYMAXFILL;
    }
    return true;
}

Token ExprLexer::getNextToken() {
    char * YYMARKER;
    const char * YYCTXMARKER;
    while(1)
    {
        ctx.tok = ctx.cur;
        if(ctx.cur == 0 && ctx.eof)
            return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);
        #line 45 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"


        if(state == 0){goto init;}
        else if(state == 1){goto linecomment;}
        else if(state == 2){goto blockcomment;}
        else if(state == 3){goto char_c;}
        else if(state == 4){goto string_c;}
        else if(state == 5){goto print;}

        init:
        
#line 55 "../lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((ctx.lim - ctx.cur) < 18) if (!ctx.fill(18)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(18);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case ' ':	goto yy6;
	case '!':	goto yy8;
	case '"':	goto yy10;
	case '%':	goto yy12;
	case '&':	goto yy14;
	case '\'':	goto yy15;
	case '(':	goto yy17;
	case ')':	goto yy19;
	case '*':	goto yy21;
	case '+':	goto yy23;
	case ',':	goto yy25;
	case '-':	goto yy27;
	case '/':	goto yy29;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	case ';':	goto yy34;
	case '<':	goto yy36;
	case '=':	goto yy38;
	case '>':	goto yy40;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'd':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	case 'R':	goto yy45;
	case 'S':	goto yy46;
	case '[':	goto yy47;
	case ']':	goto yy49;
	case 'b':	goto yy51;
	case 'c':	goto yy52;
	case 'e':	goto yy53;
	case 'f':	goto yy54;
	case 'i':	goto yy55;
	case 'n':	goto yy56;
	case 'r':	goto yy57;
	case 't':	goto yy58;
	case 'v':	goto yy59;
	case 'w':	goto yy60;
	case '{':	goto yy61;
	case '|':	goto yy63;
	case '}':	goto yy64;
	default:	goto yy4;
	}
yy2:
	++ctx.cur;
#line 114 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 156 "../lexer.cpp"
yy4:
	++ctx.cur;
yy5:
#line 115 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Error);}
#line 162 "../lexer.cpp"
yy6:
	++ctx.cur;
#line 58 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 0; continue;}
#line 167 "../lexer.cpp"
yy8:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy66;
	default:	goto yy9;
	}
yy9:
#line 101 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Not);}
#line 177 "../lexer.cpp"
yy10:
	++ctx.cur;
#line 60 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{text = "";state = 4; continue;}
#line 182 "../lexer.cpp"
yy12:
	++ctx.cur;
#line 85 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpMod);}
#line 187 "../lexer.cpp"
yy14:
	yych = *++ctx.cur;
	switch (yych) {
	case '&':	goto yy68;
	default:	goto yy5;
	}
yy15:
	++ctx.cur;
#line 59 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 3; continue;}
#line 198 "../lexer.cpp"
yy17:
	++ctx.cur;
#line 88 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpenPar);}
#line 203 "../lexer.cpp"
yy19:
	++ctx.cur;
#line 89 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::ClosePar);}
#line 208 "../lexer.cpp"
yy21:
	++ctx.cur;
#line 83 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpMul);}
#line 213 "../lexer.cpp"
yy23:
	++ctx.cur;
#line 81 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpAdd);}
#line 218 "../lexer.cpp"
yy25:
	++ctx.cur;
#line 95 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Comma);}
#line 223 "../lexer.cpp"
yy27:
	++ctx.cur;
#line 82 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpSub);}
#line 228 "../lexer.cpp"
yy29:
	yych = *++ctx.cur;
	switch (yych) {
	case '*':	goto yy70;
	case '/':	goto yy72;
	default:	goto yy30;
	}
yy30:
#line 84 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpDiv);}
#line 239 "../lexer.cpp"
yy31:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	default:	goto yy33;
	}
yy33:
#line 112 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::intConstant);}
#line 260 "../lexer.cpp"
yy34:
	++ctx.cur;
#line 94 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Semicolon);}
#line 265 "../lexer.cpp"
yy36:
	yych = *++ctx.cur;
	switch (yych) {
	case '<':	goto yy74;
	case '=':	goto yy76;
	default:	goto yy37;
	}
yy37:
#line 98 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpLess);}
#line 276 "../lexer.cpp"
yy38:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy78;
	default:	goto yy39;
	}
yy39:
#line 86 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Assign);}
#line 286 "../lexer.cpp"
yy40:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy80;
	case '>':	goto yy82;
	default:	goto yy41;
	}
yy41:
#line 97 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpGreater);}
#line 297 "../lexer.cpp"
yy42:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
yy43:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy44;
	}
yy44:
#line 113 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Id);}
#line 372 "../lexer.cpp"
yy45:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy84;
	default:	goto yy43;
	}
yy46:
	yych = *++ctx.cur;
	switch (yych) {
	case 'y':	goto yy85;
	default:	goto yy43;
	}
yy47:
	++ctx.cur;
#line 90 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpenBracket);}
#line 389 "../lexer.cpp"
yy49:
	++ctx.cur;
#line 91 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::CloseBracket);}
#line 394 "../lexer.cpp"
yy51:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy86;
	case 'r':	goto yy87;
	default:	goto yy43;
	}
yy52:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy88;
	case 'o':	goto yy89;
	default:	goto yy43;
	}
yy53:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy90;
	case 'x':	goto yy91;
	default:	goto yy43;
	}
yy54:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy92;
	case 'o':	goto yy93;
	default:	goto yy43;
	}
yy55:
	yych = *++ctx.cur;
	switch (yych) {
	case 'f':	goto yy94;
	case 'n':	goto yy96;
	default:	goto yy43;
	}
yy56:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy97;
	case 'u':	goto yy98;
	default:	goto yy43;
	}
yy57:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy99;
	case 'o':	goto yy100;
	default:	goto yy43;
	}
yy58:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy101;
	default:	goto yy43;
	}
yy59:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy102;
	default:	goto yy43;
	}
yy60:
	yych = *++ctx.cur;
	switch (yych) {
	case 'h':	goto yy103;
	default:	goto yy43;
	}
yy61:
	++ctx.cur;
#line 92 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpenBrace);}
#line 466 "../lexer.cpp"
yy63:
	yych = *++ctx.cur;
	switch (yych) {
	case '|':	goto yy104;
	default:	goto yy5;
	}
yy64:
	++ctx.cur;
#line 93 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::CloseBrace);}
#line 477 "../lexer.cpp"
yy66:
	++ctx.cur;
#line 102 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::NotEqual);}
#line 482 "../lexer.cpp"
yy68:
	++ctx.cur;
#line 103 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpAnd);}
#line 487 "../lexer.cpp"
yy70:
	++ctx.cur;
#line 56 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 2; continue;}
#line 492 "../lexer.cpp"
yy72:
	++ctx.cur;
#line 57 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 1; continue;}
#line 497 "../lexer.cpp"
yy74:
	++ctx.cur;
#line 106 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::SLL);}
#line 502 "../lexer.cpp"
yy76:
	++ctx.cur;
#line 100 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpLessEqual);}
#line 507 "../lexer.cpp"
yy78:
	++ctx.cur;
#line 105 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpEqual);}
#line 512 "../lexer.cpp"
yy80:
	++ctx.cur;
#line 99 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpGreaterEqual);}
#line 517 "../lexer.cpp"
yy82:
	++ctx.cur;
#line 107 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::SLR);}
#line 522 "../lexer.cpp"
yy84:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy106;
	default:	goto yy43;
	}
yy85:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy107;
	default:	goto yy43;
	}
yy86:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy108;
	default:	goto yy43;
	}
yy87:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy109;
	default:	goto yy43;
	}
yy88:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy110;
	default:	goto yy43;
	}
yy89:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy111;
	default:	goto yy43;
	}
yy90:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy112;
	default:	goto yy43;
	}
yy91:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy113;
	default:	goto yy43;
	}
yy92:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy114;
	default:	goto yy43;
	}
yy93:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy115;
	default:	goto yy43;
	}
yy94:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy95;
	}
yy95:
#line 71 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwIf);}
#line 654 "../lexer.cpp"
yy96:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy117;
	default:	goto yy43;
	}
yy97:
	yych = *++ctx.cur;
	switch (yych) {
	case 'w':	goto yy119;
	default:	goto yy43;
	}
yy98:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy121;
	default:	goto yy43;
	}
yy99:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy122;
	default:	goto yy43;
	}
yy100:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy123;
	default:	goto yy43;
	}
yy101:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy125;
	default:	goto yy43;
	}
yy102:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy126;
	default:	goto yy43;
	}
yy103:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy127;
	default:	goto yy43;
	}
yy104:
	++ctx.cur;
#line 104 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::OpOr);}
#line 707 "../lexer.cpp"
yy106:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy128;
	default:	goto yy43;
	}
yy107:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy129;
	default:	goto yy43;
	}
yy108:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy130;
	default:	goto yy43;
	}
yy109:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy132;
	default:	goto yy43;
	}
yy110:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy133;
	default:	goto yy43;
	}
yy111:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy134;
	default:	goto yy43;
	}
yy112:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy135;
	default:	goto yy43;
	}
yy113:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy137;
	default:	goto yy43;
	}
yy114:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy138;
	default:	goto yy43;
	}
yy115:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy116;
	}
yy116:
#line 70 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwFor);}
#line 833 "../lexer.cpp"
yy117:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy118;
	}
yy118:
#line 72 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwInt);}
#line 905 "../lexer.cpp"
yy119:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy120;
	}
yy120:
#line 73 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwNew);}
#line 977 "../lexer.cpp"
yy121:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy139;
	default:	goto yy43;
	}
yy122:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy141;
	default:	goto yy43;
	}
yy123:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy124;
	}
yy124:
#line 76 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwRot);}
#line 1061 "../lexer.cpp"
yy125:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy142;
	default:	goto yy43;
	}
yy126:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy144;
	default:	goto yy43;
	}
yy127:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy146;
	default:	goto yy43;
	}
yy128:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy147;
	default:	goto yy43;
	}
yy129:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy148;
	default:	goto yy43;
	}
yy130:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy131;
	}
yy131:
#line 63 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwBool);}
#line 1163 "../lexer.cpp"
yy132:
	yych = *++ctx.cur;
	switch (yych) {
	case 'k':	goto yy149;
	default:	goto yy43;
	}
yy133:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy151;
	default:	goto yy43;
	}
yy134:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy153;
	default:	goto yy43;
	}
yy135:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy136;
	}
yy136:
#line 67 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwElse);}
#line 1253 "../lexer.cpp"
yy137:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy154;
	default:	goto yy43;
	}
yy138:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy155;
	default:	goto yy43;
	}
yy139:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy140;
	}
yy140:
#line 74 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwNull);}
#line 1337 "../lexer.cpp"
yy141:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy157;
	default:	goto yy43;
	}
yy142:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy143;
	}
yy143:
#line 77 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwTrue);}
#line 1415 "../lexer.cpp"
yy144:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy145;
	}
yy145:
#line 78 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwVoid);}
#line 1487 "../lexer.cpp"
yy146:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy158;
	default:	goto yy43;
	}
yy147:
	yych = *++ctx.cur;
	switch (yych) {
	case 'm':	goto yy160;
	default:	goto yy43;
	}
yy148:
	yych = *++ctx.cur;
	switch (yych) {
	case 'm':	goto yy161;
	default:	goto yy43;
	}
yy149:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy150;
	}
yy150:
#line 64 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwBreak);}
#line 1577 "../lexer.cpp"
yy151:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy152;
	}
yy152:
#line 66 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwClass);}
#line 1649 "../lexer.cpp"
yy153:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy163;
	default:	goto yy43;
	}
yy154:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy164;
	default:	goto yy43;
	}
yy155:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy156;
	}
yy156:
#line 69 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwFalse);}
#line 1733 "../lexer.cpp"
yy157:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy165;
	default:	goto yy43;
	}
yy158:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy159;
	}
yy159:
#line 79 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwWhile);}
#line 1811 "../lexer.cpp"
yy160:
	yyaccept = 0;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case '.':	goto yy167;
	default:	goto yy43;
	}
yy161:
	yyaccept = 1;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case '.':	goto yy169;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy162;
	}
yy162:
#line 61 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 5; continue;}
#line 1892 "../lexer.cpp"
yy163:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy170;
	default:	goto yy43;
	}
yy164:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy171;
	default:	goto yy43;
	}
yy165:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy166;
	}
yy166:
#line 75 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwReturn);}
#line 1976 "../lexer.cpp"
yy167:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy173;
	default:	goto yy168;
	}
yy168:
	ctx.cur = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy44;
	case 1: 	goto yy162;
	default:	goto yy200;
	}
yy169:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy174;
	case 'o':	goto yy175;
	default:	goto yy168;
	}
yy170:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy176;
	default:	goto yy43;
	}
yy171:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy172;
	}
yy172:
#line 68 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwExtends);}
#line 2074 "../lexer.cpp"
yy173:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy178;
	default:	goto yy168;
	}
yy174:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy179;
	default:	goto yy168;
	}
yy175:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy180;
	default:	goto yy168;
	}
yy176:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy177;
	}
yy177:
#line 65 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwContinue);}
#line 2164 "../lexer.cpp"
yy178:
	yych = *++ctx.cur;
	switch (yych) {
	case 'x':	goto yy181;
	default:	goto yy168;
	}
yy179:
	yych = *++ctx.cur;
	switch (yych) {
	case '.':	goto yy182;
	default:	goto yy168;
	}
yy180:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy183;
	default:	goto yy168;
	}
yy181:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy184;
	default:	goto yy168;
	}
yy182:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy185;
	default:	goto yy168;
	}
yy183:
	yych = *++ctx.cur;
	switch (yych) {
	case '.':	goto yy186;
	default:	goto yy168;
	}
yy184:
	yych = *++ctx.cur;
	switch (yych) {
	case 'I':	goto yy187;
	default:	goto yy168;
	}
yy185:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy168;
	}
yy186:
	yych = *++ctx.cur;
	switch (yych) {
	case 'p':	goto yy189;
	default:	goto yy168;
	}
yy187:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy190;
	default:	goto yy168;
	}
yy188:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy191;
	default:	goto yy168;
	}
yy189:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy192;
	default:	goto yy168;
	}
yy190:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy193;
	default:	goto yy168;
	}
yy191:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy195;
	default:	goto yy168;
	}
yy192:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy197;
	default:	goto yy168;
	}
yy193:
	++ctx.cur;
#line 111 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwRandom);}
#line 2259 "../lexer.cpp"
yy195:
	++ctx.cur;
#line 110 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwRead);}
#line 2264 "../lexer.cpp"
yy197:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy168;
	}
yy198:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy199;
	default:	goto yy168;
	}
yy199:
	yyaccept = 2;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case 'l':	goto yy201;
	default:	goto yy200;
	}
yy200:
#line 109 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwPrint);}
#line 2287 "../lexer.cpp"
yy201:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy202;
	default:	goto yy168;
	}
yy202:
	++ctx.cur;
#line 108 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::KwPrintln);}
#line 2298 "../lexer.cpp"
}
#line 116 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

        linecomment:
        
#line 2304 "../lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy206;
	case '\n':	goto yy210;
	default:	goto yy208;
	}
yy206:
	++ctx.cur;
#line 121 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 2318 "../lexer.cpp"
yy208:
	++ctx.cur;
#line 120 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 1; continue;}
#line 2323 "../lexer.cpp"
yy210:
	++ctx.cur;
#line 119 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 0; continue;}
#line 2328 "../lexer.cpp"
}
#line 122 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

        blockcomment:
        
#line 2334 "../lexer.cpp"
{
	char yych;
	if ((ctx.lim - ctx.cur) < 2) if (!ctx.fill(2)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(2);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy214;
	case '*':	goto yy218;
	default:	goto yy216;
	}
yy214:
	++ctx.cur;
#line 127 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 2348 "../lexer.cpp"
yy216:
	++ctx.cur;
yy217:
#line 126 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 2; continue;}
#line 2354 "../lexer.cpp"
yy218:
	yych = *++ctx.cur;
	switch (yych) {
	case '/':	goto yy219;
	default:	goto yy217;
	}
yy219:
	++ctx.cur;
#line 125 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 0; continue;}
#line 2365 "../lexer.cpp"
}
#line 129 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

        char_c:
        
#line 2371 "../lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy224;
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy226;
	case '\'':	goto yy228;
	default:	goto yy223;
	}
yy223:
yy224:
	++ctx.cur;
#line 139 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 2480 "../lexer.cpp"
yy226:
	++ctx.cur;
#line 133 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{   
                                                std::string temp(ctx.tok, ctx.cur-ctx.tok);
                                                text = std::move(temp);
                                                state = 3; 
                                                continue;
                                            }
#line 2490 "../lexer.cpp"
yy228:
	++ctx.cur;
#line 132 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 0;return Token::CharConstant;}
#line 2495 "../lexer.cpp"
}
#line 140 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

        string_c:
        
#line 2501 "../lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy233;
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy235;
	case '"':	goto yy238;
	default:	goto yy232;
	}
yy232:
yy233:
	++ctx.cur;
#line 150 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 2610 "../lexer.cpp"
yy235:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	switch (yych) {
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy235;
	default:	goto yy237;
	}
yy237:
#line 144 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{   
                                                std::string temp(ctx.tok, ctx.cur-ctx.tok);
                                                text += std::move(temp);
                                                state = 4; 
                                                continue;
                                            }
#line 2720 "../lexer.cpp"
yy238:
	++ctx.cur;
#line 143 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 0;return Token::StringConstant;}
#line 2725 "../lexer.cpp"
}
#line 151 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

        print:
        
#line 2731 "../lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);(1);
	yych = *ctx.cur;
	if (yych >= 0x01) goto yy244;
	++ctx.cur;
#line 155 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,Token::Eof);}
#line 2740 "../lexer.cpp"
yy244:
	++ctx.cur;
#line 154 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"
	{state = 2; continue;}
#line 2745 "../lexer.cpp"
}
#line 157 "/home/boris/Desktop/CompiladoresII/Proyecto/expr_lexer.re"

    }
}

/*

*/