/* Generated by re2c 1.1.1 on Mon Mar 25 06:52:20 2019 */
#line 1 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
#include <cstdio>
#include "expr_lexer.h"

#define YYMAXFILL 18

int lineNo=1;

int ExprLexer::Context::fill(size_t need)
{
    if(eof)
        return 1;
    
    const size_t free = tok - buf;
    if(free<need)
        return 2;

    memmove(buf, tok, lim-tok);
    lim -= free;
    cur -= free;
    tok -= free;
    in.read(buf,free);
    lim += in.gcount();
    
    if(lim < buf + free)
    {
        eof = true;
        memset(lim,0,YYMAXFILL);
        lim+=YYMAXFILL;
    }
    return 3;
}

int ExprLexer::getNextToken() {
    char * YYMARKER;
    const char * YYCTXMARKER;
    while(1)
    {
        ctx.tok = ctx.cur;
        if(ctx.cur == 0 && ctx.eof)
            return 0;
        #line 46 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"


        if(state == 0){goto init;}
        else if(state == 1){goto linecomment;}
        else if(state == 2){goto blockcomment;}
        else if(state == 3){goto char_c;}
        else if(state == 4){goto string_c;}
        else if(state == 5){goto print;}

        init:
        
#line 56 "../src/lexer.cpp"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((ctx.lim - ctx.cur) < 18) if (!ctx.fill(18)) return 0;(18);
	yych = *ctx.cur;
	switch (yych) {
	case 0x00:	goto yy3;
	case '\t':
	case ' ':	goto yy5;
	case '\n':	goto yy7;
	case '!':	goto yy9;
	case '"':	goto yy11;
	case '%':	goto yy13;
	case '&':	goto yy15;
	case '\'':	goto yy16;
	case '(':	goto yy18;
	case ')':	goto yy20;
	case '*':	goto yy22;
	case '+':	goto yy24;
	case ',':	goto yy26;
	case '-':	goto yy28;
	case '/':	goto yy30;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	case ';':	goto yy35;
	case '<':	goto yy37;
	case '=':	goto yy39;
	case '>':	goto yy41;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'd':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 'u':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	case 'R':	goto yy46;
	case 'S':	goto yy47;
	case '[':	goto yy48;
	case ']':	goto yy50;
	case 'b':	goto yy52;
	case 'c':	goto yy53;
	case 'e':	goto yy54;
	case 'f':	goto yy55;
	case 'i':	goto yy56;
	case 'n':	goto yy57;
	case 'r':	goto yy58;
	case 't':	goto yy59;
	case 'v':	goto yy60;
	case 'w':	goto yy61;
	case '{':	goto yy62;
	case '|':	goto yy64;
	case '}':	goto yy65;
	default:	goto yy2;
	}
yy2:
	ctx.cur = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy45;
	case 1: 	goto yy163;
	default:	goto yy200;
	}
yy3:
	++ctx.cur;
#line 136 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return 0;}
#line 164 "../src/lexer.cpp"
yy5:
	++ctx.cur;
#line 59 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 0; continue;}
#line 169 "../src/lexer.cpp"
yy7:
	++ctx.cur;
#line 60 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{lineNo++;continue;}
#line 174 "../src/lexer.cpp"
yy9:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy67;
	default:	goto yy10;
	}
yy10:
#line 115 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::Not);}
#line 184 "../src/lexer.cpp"
yy11:
	++ctx.cur;
#line 62 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{text = "";state = 4; continue;}
#line 189 "../src/lexer.cpp"
yy13:
	++ctx.cur;
#line 99 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpMod);}
#line 194 "../src/lexer.cpp"
yy15:
	yych = *++ctx.cur;
	switch (yych) {
	case '&':	goto yy69;
	default:	goto yy2;
	}
yy16:
	++ctx.cur;
#line 61 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 3; continue;}
#line 205 "../src/lexer.cpp"
yy18:
	++ctx.cur;
#line 102 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpenPar);}
#line 210 "../src/lexer.cpp"
yy20:
	++ctx.cur;
#line 103 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::ClosePar);}
#line 215 "../src/lexer.cpp"
yy22:
	++ctx.cur;
#line 97 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpMul);}
#line 220 "../src/lexer.cpp"
yy24:
	++ctx.cur;
#line 95 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpAdd);}
#line 225 "../src/lexer.cpp"
yy26:
	++ctx.cur;
#line 109 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::Comma);}
#line 230 "../src/lexer.cpp"
yy28:
	++ctx.cur;
#line 96 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpSub);}
#line 235 "../src/lexer.cpp"
yy30:
	yych = *++ctx.cur;
	switch (yych) {
	case '*':	goto yy71;
	case '/':	goto yy73;
	default:	goto yy31;
	}
yy31:
#line 98 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpDiv);}
#line 246 "../src/lexer.cpp"
yy32:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy32;
	default:	goto yy34;
	}
yy34:
#line 126 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{
                                            yytokentype tok = makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::intConstant);
                                            yylval.int_t = atol(text.c_str());
                                            return tok;
                                        }
#line 271 "../src/lexer.cpp"
yy35:
	++ctx.cur;
#line 108 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::Semicolon);}
#line 276 "../src/lexer.cpp"
yy37:
	yych = *++ctx.cur;
	switch (yych) {
	case '<':	goto yy75;
	case '=':	goto yy77;
	default:	goto yy38;
	}
yy38:
#line 112 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpLess);}
#line 287 "../src/lexer.cpp"
yy39:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy79;
	default:	goto yy40;
	}
yy40:
#line 100 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::Assign);}
#line 297 "../src/lexer.cpp"
yy41:
	yych = *++ctx.cur;
	switch (yych) {
	case '=':	goto yy81;
	case '>':	goto yy83;
	default:	goto yy42;
	}
yy42:
#line 111 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpGreater);}
#line 308 "../src/lexer.cpp"
yy43:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
yy44:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy45;
	}
yy45:
#line 131 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{
                                            yytokentype tok = makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::Id);
                                            yylval.str_t = strdup(text.c_str());
                                            return tok;
                                        }
#line 387 "../src/lexer.cpp"
yy46:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy85;
	default:	goto yy44;
	}
yy47:
	yych = *++ctx.cur;
	switch (yych) {
	case 'y':	goto yy86;
	default:	goto yy44;
	}
yy48:
	++ctx.cur;
#line 104 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpenBracket);}
#line 404 "../src/lexer.cpp"
yy50:
	++ctx.cur;
#line 105 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::CloseBracket);}
#line 409 "../src/lexer.cpp"
yy52:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy87;
	case 'r':	goto yy88;
	default:	goto yy44;
	}
yy53:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy89;
	case 'o':	goto yy90;
	default:	goto yy44;
	}
yy54:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy91;
	case 'x':	goto yy92;
	default:	goto yy44;
	}
yy55:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy93;
	case 'o':	goto yy94;
	default:	goto yy44;
	}
yy56:
	yych = *++ctx.cur;
	switch (yych) {
	case 'f':	goto yy95;
	case 'n':	goto yy97;
	default:	goto yy44;
	}
yy57:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy98;
	case 'u':	goto yy99;
	default:	goto yy44;
	}
yy58:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy100;
	case 'o':	goto yy101;
	default:	goto yy44;
	}
yy59:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy102;
	default:	goto yy44;
	}
yy60:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy103;
	default:	goto yy44;
	}
yy61:
	yych = *++ctx.cur;
	switch (yych) {
	case 'h':	goto yy104;
	default:	goto yy44;
	}
yy62:
	++ctx.cur;
#line 106 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpenBrace);}
#line 481 "../src/lexer.cpp"
yy64:
	yych = *++ctx.cur;
	switch (yych) {
	case '|':	goto yy105;
	default:	goto yy2;
	}
yy65:
	++ctx.cur;
#line 107 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::CloseBrace);}
#line 492 "../src/lexer.cpp"
yy67:
	++ctx.cur;
#line 116 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::NotEqual);}
#line 497 "../src/lexer.cpp"
yy69:
	++ctx.cur;
#line 117 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpAnd);}
#line 502 "../src/lexer.cpp"
yy71:
	++ctx.cur;
#line 57 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 2; continue;}
#line 507 "../src/lexer.cpp"
yy73:
	++ctx.cur;
#line 58 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 1; continue;}
#line 512 "../src/lexer.cpp"
yy75:
	++ctx.cur;
#line 120 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::SLL);}
#line 517 "../src/lexer.cpp"
yy77:
	++ctx.cur;
#line 114 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpLessEqual);}
#line 522 "../src/lexer.cpp"
yy79:
	++ctx.cur;
#line 119 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpEqual);}
#line 527 "../src/lexer.cpp"
yy81:
	++ctx.cur;
#line 113 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpGreaterEqual);}
#line 532 "../src/lexer.cpp"
yy83:
	++ctx.cur;
#line 121 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::SLR);}
#line 537 "../src/lexer.cpp"
yy85:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy107;
	default:	goto yy44;
	}
yy86:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy108;
	default:	goto yy44;
	}
yy87:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy109;
	default:	goto yy44;
	}
yy88:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy110;
	default:	goto yy44;
	}
yy89:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy111;
	default:	goto yy44;
	}
yy90:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy112;
	default:	goto yy44;
	}
yy91:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy113;
	default:	goto yy44;
	}
yy92:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy114;
	default:	goto yy44;
	}
yy93:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy115;
	default:	goto yy44;
	}
yy94:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy116;
	default:	goto yy44;
	}
yy95:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy96;
	}
yy96:
#line 77 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwIf);}
#line 669 "../src/lexer.cpp"
yy97:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy118;
	default:	goto yy44;
	}
yy98:
	yych = *++ctx.cur;
	switch (yych) {
	case 'w':	goto yy120;
	default:	goto yy44;
	}
yy99:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy122;
	default:	goto yy44;
	}
yy100:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy123;
	default:	goto yy44;
	}
yy101:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy124;
	default:	goto yy44;
	}
yy102:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy126;
	default:	goto yy44;
	}
yy103:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy127;
	default:	goto yy44;
	}
yy104:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy128;
	default:	goto yy44;
	}
yy105:
	++ctx.cur;
#line 118 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::OpOr);}
#line 722 "../src/lexer.cpp"
yy107:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy129;
	default:	goto yy44;
	}
yy108:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy130;
	default:	goto yy44;
	}
yy109:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy131;
	default:	goto yy44;
	}
yy110:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy133;
	default:	goto yy44;
	}
yy111:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy134;
	default:	goto yy44;
	}
yy112:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy135;
	default:	goto yy44;
	}
yy113:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy136;
	default:	goto yy44;
	}
yy114:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy138;
	default:	goto yy44;
	}
yy115:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy139;
	default:	goto yy44;
	}
yy116:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy117;
	}
yy117:
#line 76 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwFor);}
#line 848 "../src/lexer.cpp"
yy118:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy119;
	}
yy119:
#line 78 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{
                                            yytokentype tok = makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwInt);
                                            yylval.str_t = strdup(text.c_str());
                                            return tok;
                                        }
#line 924 "../src/lexer.cpp"
yy120:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy121;
	}
yy121:
#line 83 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwNew);}
#line 996 "../src/lexer.cpp"
yy122:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy140;
	default:	goto yy44;
	}
yy123:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy142;
	default:	goto yy44;
	}
yy124:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy125;
	}
yy125:
#line 86 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwRot);}
#line 1080 "../src/lexer.cpp"
yy126:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy143;
	default:	goto yy44;
	}
yy127:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy145;
	default:	goto yy44;
	}
yy128:
	yych = *++ctx.cur;
	switch (yych) {
	case 'l':	goto yy147;
	default:	goto yy44;
	}
yy129:
	yych = *++ctx.cur;
	switch (yych) {
	case 'o':	goto yy148;
	default:	goto yy44;
	}
yy130:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy149;
	default:	goto yy44;
	}
yy131:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy132;
	}
yy132:
#line 65 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{
                                            yytokentype tok = makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwBool);
                                            yylval.str_t = strdup(text.c_str());
                                            return tok;                                            
                                        }
#line 1186 "../src/lexer.cpp"
yy133:
	yych = *++ctx.cur;
	switch (yych) {
	case 'k':	goto yy150;
	default:	goto yy44;
	}
yy134:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy152;
	default:	goto yy44;
	}
yy135:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy154;
	default:	goto yy44;
	}
yy136:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy137;
	}
yy137:
#line 73 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwElse);}
#line 1276 "../src/lexer.cpp"
yy138:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy155;
	default:	goto yy44;
	}
yy139:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy156;
	default:	goto yy44;
	}
yy140:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy141;
	}
yy141:
#line 84 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwNull);}
#line 1360 "../src/lexer.cpp"
yy142:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy158;
	default:	goto yy44;
	}
yy143:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy144;
	}
yy144:
#line 87 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwTrue);}
#line 1438 "../src/lexer.cpp"
yy145:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy146;
	}
yy146:
#line 88 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{
                                            yytokentype tok = makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwVoid);
                                            yylval.str_t = strdup(text.c_str());
                                            return tok;
                                        }
#line 1514 "../src/lexer.cpp"
yy147:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy159;
	default:	goto yy44;
	}
yy148:
	yych = *++ctx.cur;
	switch (yych) {
	case 'm':	goto yy161;
	default:	goto yy44;
	}
yy149:
	yych = *++ctx.cur;
	switch (yych) {
	case 'm':	goto yy162;
	default:	goto yy44;
	}
yy150:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy151;
	}
yy151:
#line 70 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwBreak);}
#line 1604 "../src/lexer.cpp"
yy152:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy153;
	}
yy153:
#line 72 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwClass);}
#line 1676 "../src/lexer.cpp"
yy154:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy164;
	default:	goto yy44;
	}
yy155:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy165;
	default:	goto yy44;
	}
yy156:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy157;
	}
yy157:
#line 75 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwFalse);}
#line 1760 "../src/lexer.cpp"
yy158:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy166;
	default:	goto yy44;
	}
yy159:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy160;
	}
yy160:
#line 93 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwWhile);}
#line 1838 "../src/lexer.cpp"
yy161:
	yyaccept = 0;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case '.':	goto yy168;
	default:	goto yy44;
	}
yy162:
	yyaccept = 1;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case '.':	goto yy169;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy163;
	}
yy163:
#line 63 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 5; continue;}
#line 1919 "../src/lexer.cpp"
yy164:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy170;
	default:	goto yy44;
	}
yy165:
	yych = *++ctx.cur;
	switch (yych) {
	case 's':	goto yy171;
	default:	goto yy44;
	}
yy166:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy167;
	}
yy167:
#line 85 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwReturn);}
#line 2003 "../src/lexer.cpp"
yy168:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy173;
	default:	goto yy2;
	}
yy169:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy174;
	case 'o':	goto yy175;
	default:	goto yy2;
	}
yy170:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy176;
	default:	goto yy44;
	}
yy171:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy172;
	}
yy172:
#line 74 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwExtends);}
#line 2094 "../src/lexer.cpp"
yy173:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy178;
	default:	goto yy2;
	}
yy174:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy179;
	default:	goto yy2;
	}
yy175:
	yych = *++ctx.cur;
	switch (yych) {
	case 'u':	goto yy180;
	default:	goto yy2;
	}
yy176:
	yych = *++ctx.cur;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy43;
	default:	goto yy177;
	}
yy177:
#line 71 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwContinue);}
#line 2184 "../src/lexer.cpp"
yy178:
	yych = *++ctx.cur;
	switch (yych) {
	case 'x':	goto yy181;
	default:	goto yy2;
	}
yy179:
	yych = *++ctx.cur;
	switch (yych) {
	case '.':	goto yy182;
	default:	goto yy2;
	}
yy180:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy183;
	default:	goto yy2;
	}
yy181:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy184;
	default:	goto yy2;
	}
yy182:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy185;
	default:	goto yy2;
	}
yy183:
	yych = *++ctx.cur;
	switch (yych) {
	case '.':	goto yy186;
	default:	goto yy2;
	}
yy184:
	yych = *++ctx.cur;
	switch (yych) {
	case 'I':	goto yy187;
	default:	goto yy2;
	}
yy185:
	yych = *++ctx.cur;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy2;
	}
yy186:
	yych = *++ctx.cur;
	switch (yych) {
	case 'p':	goto yy189;
	default:	goto yy2;
	}
yy187:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy190;
	default:	goto yy2;
	}
yy188:
	yych = *++ctx.cur;
	switch (yych) {
	case 'a':	goto yy191;
	default:	goto yy2;
	}
yy189:
	yych = *++ctx.cur;
	switch (yych) {
	case 'r':	goto yy192;
	default:	goto yy2;
	}
yy190:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy193;
	default:	goto yy2;
	}
yy191:
	yych = *++ctx.cur;
	switch (yych) {
	case 'd':	goto yy195;
	default:	goto yy2;
	}
yy192:
	yych = *++ctx.cur;
	switch (yych) {
	case 'i':	goto yy197;
	default:	goto yy2;
	}
yy193:
	++ctx.cur;
#line 125 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwRandom);}
#line 2279 "../src/lexer.cpp"
yy195:
	++ctx.cur;
#line 124 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwRead);}
#line 2284 "../src/lexer.cpp"
yy197:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy198;
	default:	goto yy2;
	}
yy198:
	yych = *++ctx.cur;
	switch (yych) {
	case 't':	goto yy199;
	default:	goto yy2;
	}
yy199:
	yyaccept = 2;
	yych = *(YYMARKER = ++ctx.cur);
	switch (yych) {
	case 'l':	goto yy201;
	default:	goto yy200;
	}
yy200:
#line 123 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwPrint);}
#line 2307 "../src/lexer.cpp"
yy201:
	yych = *++ctx.cur;
	switch (yych) {
	case 'n':	goto yy202;
	default:	goto yy2;
	}
yy202:
	++ctx.cur;
#line 122 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{return makeToken(ctx.tok,ctx.cur-ctx.tok,yytokentype::KwPrintln);}
#line 2318 "../src/lexer.cpp"
}
#line 137 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

        linecomment:
        
#line 2324 "../src/lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
	switch (yych) {
	case '\n':	goto yy208;
	default:	goto yy206;
	}
yy206:
	++ctx.cur;
#line 141 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 1; continue;}
#line 2337 "../src/lexer.cpp"
yy208:
	++ctx.cur;
#line 140 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{lineNo++; state = 0; continue;}
#line 2342 "../src/lexer.cpp"
}
#line 142 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

        blockcomment:
        
#line 2348 "../src/lexer.cpp"
{
	char yych;
	if ((ctx.lim - ctx.cur) < 2) if (!ctx.fill(2)) return 0;(2);
	yych = *ctx.cur;
	switch (yych) {
	case '\n':	goto yy214;
	case '*':	goto yy216;
	default:	goto yy212;
	}
yy212:
	++ctx.cur;
yy213:
#line 147 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 2; continue;}
#line 2363 "../src/lexer.cpp"
yy214:
	++ctx.cur;
#line 146 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{lineNo++; state = 2; continue;}
#line 2368 "../src/lexer.cpp"
yy216:
	yych = *++ctx.cur;
	switch (yych) {
	case '/':	goto yy217;
	default:	goto yy213;
	}
yy217:
	++ctx.cur;
#line 145 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 0; continue;}
#line 2379 "../src/lexer.cpp"
}
#line 150 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

        char_c:
        
#line 2385 "../src/lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
	switch (yych) {
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy222;
	case '\'':	goto yy224;
	default:	goto yy221;
	}
yy221:
yy222:
	++ctx.cur;
#line 154 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{   
                                                std::string temp(ctx.tok, ctx.cur-ctx.tok);
                                                text = std::move(temp);
                                                state = 3; 
                                                continue;
                                            }
#line 2498 "../src/lexer.cpp"
yy224:
	++ctx.cur;
#line 153 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 0;yylval.str_t = strdup(text.c_str());return yytokentype::CharConstant;}
#line 2503 "../src/lexer.cpp"
}
#line 160 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

        string_c:
        
#line 2509 "../src/lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
	switch (yych) {
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy229;
	case '"':	goto yy232;
	default:	goto yy228;
	}
yy228:
yy229:
	++ctx.cur;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur;
	switch (yych) {
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case '\\':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:	goto yy229;
	default:	goto yy231;
	}
yy231:
#line 164 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{   
                                                std::string temp(ctx.tok, ctx.cur-ctx.tok);
                                                text += std::move(temp);
                                                state = 4; 
                                                continue;
                                            }
#line 2722 "../src/lexer.cpp"
yy232:
	++ctx.cur;
#line 163 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 0;yylval.str_t = strdup(text.c_str());return yytokentype::StringConstant;}
#line 2727 "../src/lexer.cpp"
}
#line 170 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

        print:
        
#line 2733 "../src/lexer.cpp"
{
	char yych;
	if (ctx.lim <= ctx.cur) if (!ctx.fill(1)) return 0;(1);
	yych = *ctx.cur++;
#line 173 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"
	{state = 2; continue;}
#line 2740 "../src/lexer.cpp"
}
#line 175 "/home/boris/Desktop/Proyecto/src/expr_lexer.re"

    }
}

/*

*/